version: '3.8'

services:
  postgres-user-db:
    image: postgres:latest
    container_name: postgres-user-container
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=user_service
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    networks:
      - classroom-network

  postgres-class-db:
    image: postgres:latest
    container_name: postgres-class-container
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=class_service
    volumes:
      - postgres_class_data:/var/lib/postgresql/data
    networks:
      - classroom-network

  minio:
    image: minio/minio:latest
    container_name: minio-storage
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: supersecretpassword
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - classroom-network

  user-service:
    image: phucngo249/user-service:latest
    container_name: user-service-app
    restart: always
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres-user-db
      - DB_PORT=5432
      - DB_NAME=user_service
      - DB_USER=postgres
      - DB_PASSWORD=123
    depends_on:
      - postgres-user-db
    networks:
      - classroom-network

  class-service:
    image: phucngo249/class-service:latest
    container_name: class-service-app
    restart: always
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=postgres-class-db
      - DB_PORT=5432
      - DB_NAME=class_service
      - DB_USER=postgres
      - DB_PASSWORD=123
      - USER_SERVICE_URL=http://user-service-app:8081
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=supersecretpassword
      - MINIO_BUCKET=classroom-materials
      - APP_ALLOWED_ORIGINS=http://localhost:5173
      - APP_JWT_SECRET=3c963655447b567565b90214e9f7f0bc62e1e07b7134017326dfbf0800b6ed5b
    depends_on:
      - postgres-class-db
      - minio
    networks:
      - classroom-network

  frontend:
    image: phucngo249/classroom-frontend:latest
    container_name: classroom-frontend-app
    restart: always
    ports:
      - "5173:80"
    networks:
      - classroom-network
    depends_on:
      - user-service
      - class-service

volumes:
  postgres_user_data:
  postgres_class_data:
  minio_data:

networks:
  classroom-network:
    driver: bridge