services:
  discovery-service:
    build:
      context: .
      dockerfile: discovery_service/Dockerfile
    image: phucngo249/discovery-service:latest
    container_name: discovery-service-app
    restart: always
    ports:
      - "8761:8761"
    networks:
      - classroom-network

  postgres-user-db:
    image: postgres:15-alpine
    container_name: postgres-user-container
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=user_service
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    networks:
      - classroom-network

  postgres-class-db:
    image: postgres:15-alpine
    container_name: postgres-class-container
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=class_service
    volumes:
      - postgres_class_data:/var/lib/postgresql/data
    networks:
      - classroom-network

  minio:
    image: minio/minio:latest
    container_name: minio-storage
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: supersecretpassword
    volumes:
      - minio_data:/data
    command: server /data --address ":9000" --console-address ":9001"
    networks:
      - classroom-network

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    image: phucngo249/user-service:latest
    container_name: user-service-app
    restart: always
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres-user-db
      - DB_PORT=5432
      - DB_NAME=user_service
      - DB_USER=postgres
      - DB_PASSWORD=123
      - APP_JWT_SECRET=3c963655447b567565b90214e9f7f0bc62e1e07b7134017326dfbf0800b6ed5b
      - EUREKA_URL=http://discovery-service-app:8761/eureka/
    depends_on:
      - postgres-user-db
      - discovery-service
    networks:
      - classroom-network

  class-service:
    build:
      context: .
      dockerfile: class_service/Dockerfile
    image: phucngo249/class-service:latest
    container_name: class-service-app
    restart: always
    ports:
      - "8082:8082"
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      - DB_HOST=postgres-class-db
      - DB_PORT=5432
      - DB_NAME=class_service
      - DB_USER=postgres
      - DB_PASSWORD=123
      - MINIO_ENDPOINT=http://localhost:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=supersecretpassword
      - MINIO_BUCKET=classroom-materials
      - APP_ALLOWED_ORIGINS=http://localhost:5173,http://192.168.66.133:5173
      - APP_JWT_SECRET=3c963655447b567565b90214e9f7f0bc62e1e07b7134017326dfbf0800b6ed5b
      - USER_SERVICE_URL=http://user-service:8081
      - EUREKA_URL=http://discovery-service-app:8761/eureka/
    depends_on:
      postgres-class-db:
        condition: service_started
      minio:
        condition: service_started
      discovery-service:
        condition: service_started
    networks:
      - classroom-network

volumes:
  postgres_user_data:
  postgres_class_data:
  minio_data:

networks:
  classroom-network:
    driver: bridge