services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-classroom
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "0917635632Mysql"
      MYSQL_DATABASE: "user_service"
    volumes:
      - mysql_classroom_data:/var/lib/mysql
    networks:
      - classroom-network

  user-service:
    image: phucngo249/user-service:latest
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service-app
    restart: always
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=mysql-db
      - DB_NAME=user_service
      - DB_USER=root
      - DB_PASSWORD=0917635632Mysql
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://192.168.66.133:5173
    depends_on:
      - mysql-db
    networks:
      - classroom-network

  class-service:
    image: phucngo249/class-service:latest
    build:
      context: .
      dockerfile: class-service/Dockerfile
    container_name: class-service-app
    restart: always
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=mysql-db
      - DB_NAME=class_service
      - DB_USER=root
      - DB_PASSWORD=0917635632Mysql
      - USER_SERVICE_HOST=user-service
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://192.168.66.133:5173
    depends_on:
      - mysql-db
      - user-service
    networks:
      - classroom-network

volumes:
  mysql_classroom_data:

networks:
  classroom-network:
    driver: bridge